# Generated by Django 6.0.3 on 2026-03-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='title',
        ),
    ]
