# Generated by Django 6.0.3 on 2026-03-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='India', max_length=100),
            preserve_default=False,
        ),
    ]
