# Generated by Django 6.0.3 on 2026-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='country_code',
            field=models.CharField(default='in', max_length=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(max_length=500),
        ),
    ]
