# Generated by Django 6.0.3 on 2026-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_country_code_alter_trip_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='ai_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
