# Generated by Django 6.0.3 on 2026-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_ai_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
